### ISSUE TITLE
logWithTime wordt te vaak aangeroepen

### ISSUE THREAD

**Issue by bobvandenberge** [ROCHatty/All-the-loggers-592793a3#1]
De functie `$this -> logWithTime();` wordt bij elke functie aangeroepen, dat is niet de bedoeling. De log functie zou de 'logWithTime' moeten aanroepen, dan is die maar 1 keer nodig.

**Comment by ROCHatty** [comment]
Dat komt doordat https://jarvis.bit-academy.nl/a/code/modules/b578d3b3-0a9f-11ea-ab6c-cec41367f4e7/levels/761b039d-0aa1-11ea-ab6c-cec41367f4e7/exercises/916ed37f-104e-11ea-ab6c-cec41367f4e7 zei dat alleen de `warn` en `error` functie de tijd moesten aangeven, maar toen stond er in de voorbeelden van de andere opdrachten daarna dat alle functies tijden hadden.

Ja, en toen heb ik het maar gewoon bij al die functies erbij geplakt, maar heb het nu gefixt.
